/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/Masthead copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HistoChart: typeof import('./src/components/HistoChart.vue')['default']
    Lighthouse_spot: typeof import('./src/components/Lighthouse_spot.vue')['default']
    Masthead: typeof import('./src/components/Masthead.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    PageWeightChart: typeof import('./src/components/PageWeightChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
